export interface HabitTemplate {
  title: string
  icon: string
  color: string
  category: 'content_creative' | 'learning' | 'health_fitness' | 'networking_career'
  goalType: 'binary' | 'count'
  target: number | null
  unit: string | null
  frequency: { type: string; daysOfWeek?: number[] }
  defaultReminderTime: string // HH:MM
}

export const habitGallery: HabitTemplate[] = [
  // ── Content & Creative ──────────────────────────────────────
  {
    title: 'Write LinkedIn post',
    icon: 'Pencil',
    color: '#0A66C2',
    category: 'content_creative',
    goalType: 'binary',
    target: null,
    unit: null,
    frequency: { type: 'daily', daysOfWeek: [1, 2, 3, 4, 5] },
    defaultReminderTime: '09:00',
  },
  {
    title: 'Publish blog post',
    icon: 'FileText',
    color: '#8B5CF6',
    category: 'content_creative',
    goalType: 'count',
    target: 1,
    unit: 'posts',
    frequency: { type: 'daily', daysOfWeek: [0, 1, 2, 3, 4, 5, 6] },
    defaultReminderTime: '10:00',
  },
  {
    title: 'Post Instagram reel',
    icon: 'Video',
    color: '#E1306C',
    category: 'content_creative',
    goalType: 'binary',
    target: null,
    unit: null,
    frequency: { type: 'daily', daysOfWeek: [1, 3, 5] },
    defaultReminderTime: '11:00',
  },
  {
    title: 'Draft X thread',
    icon: 'MessageSquare',
    color: '#1DA1F2',
    category: 'content_creative',
    goalType: 'binary',
    target: null,
    unit: null,
    frequency: { type: 'daily', daysOfWeek: [1, 2, 3, 4, 5] },
    defaultReminderTime: '08:00',
  },
  {
    title: 'Record podcast episode',
    icon: 'Mic',
    color: '#7C3AED',
    category: 'content_creative',
    goalType: 'binary',
    target: null,
    unit: null,
    frequency: { type: 'daily', daysOfWeek: [2, 4] },
    defaultReminderTime: '14:00',
  },

  // ── Learning ────────────────────────────────────────────────
  {
    title: 'Read 30 pages',
    icon: 'Book',
    color: '#F59E0B',
    category: 'learning',
    goalType: 'count',
    target: 30,
    unit: 'pages',
    frequency: { type: 'daily' },
    defaultReminderTime: '20:00',
  },
  {
    title: 'Take course module',
    icon: 'GraduationCap',
    color: '#10B981',
    category: 'learning',
    goalType: 'count',
    target: 1,
    unit: 'modules',
    frequency: { type: 'daily', daysOfWeek: [1, 2, 3, 4, 5] },
    defaultReminderTime: '19:00',
  },
  {
    title: 'Practice language',
    icon: 'Globe',
    color: '#06B6D4',
    category: 'learning',
    goalType: 'count',
    target: 15,
    unit: 'minutes',
    frequency: { type: 'daily' },
    defaultReminderTime: '07:30',
  },
  {
    title: 'Watch tutorial',
    icon: 'Play',
    color: '#EF4444',
    category: 'learning',
    goalType: 'count',
    target: 1,
    unit: 'videos',
    frequency: { type: 'daily', daysOfWeek: [1, 3, 5] },
    defaultReminderTime: '18:00',
  },
  {
    title: 'Write notes',
    icon: 'StickyNote',
    color: '#F97316',
    category: 'learning',
    goalType: 'binary',
    target: null,
    unit: null,
    frequency: { type: 'daily' },
    defaultReminderTime: '21:00',
  },

  // ── Health & Fitness ────────────────────────────────────────
  {
    title: 'Gym workout',
    icon: 'Dumbbell',
    color: '#EF4444',
    category: 'health_fitness',
    goalType: 'binary',
    target: null,
    unit: null,
    frequency: { type: 'daily', daysOfWeek: [1, 2, 3, 4, 5] },
    defaultReminderTime: '06:00',
  },
  {
    title: 'Swim 30 min',
    icon: 'Waves',
    color: '#3B82F6',
    category: 'health_fitness',
    goalType: 'count',
    target: 30,
    unit: 'minutes',
    frequency: { type: 'daily', daysOfWeek: [1, 3, 5] },
    defaultReminderTime: '07:00',
  },
  {
    title: '10k steps',
    icon: 'Footprints',
    color: '#22C55E',
    category: 'health_fitness',
    goalType: 'count',
    target: 10000,
    unit: 'steps',
    frequency: { type: 'daily' },
    defaultReminderTime: '18:00',
  },
  {
    title: 'Drink 2L water',
    icon: 'Droplets',
    color: '#38BDF8',
    category: 'health_fitness',
    goalType: 'count',
    target: 2000,
    unit: 'ml',
    frequency: { type: 'daily' },
    defaultReminderTime: '08:00',
  },
  {
    title: 'Meditate 10 min',
    icon: 'Brain',
    color: '#A78BFA',
    category: 'health_fitness',
    goalType: 'count',
    target: 10,
    unit: 'minutes',
    frequency: { type: 'daily' },
    defaultReminderTime: '06:30',
  },

  // ── Networking & Career ─────────────────────────────────────
  {
    title: 'Attend networking event',
    icon: 'Users',
    color: '#6366F1',
    category: 'networking_career',
    goalType: 'binary',
    target: null,
    unit: null,
    frequency: { type: 'daily', daysOfWeek: [3] },
    defaultReminderTime: '10:00',
  },
  {
    title: 'DM 3 people',
    icon: 'Send',
    color: '#14B8A6',
    category: 'networking_career',
    goalType: 'count',
    target: 3,
    unit: 'messages',
    frequency: { type: 'daily', daysOfWeek: [1, 2, 3, 4, 5] },
    defaultReminderTime: '09:00',
  },
  {
    title: 'Apply to 2 jobs',
    icon: 'Briefcase',
    color: '#F59E0B',
    category: 'networking_career',
    goalType: 'count',
    target: 2,
    unit: 'applications',
    frequency: { type: 'daily', daysOfWeek: [1, 2, 3, 4, 5] },
    defaultReminderTime: '10:00',
  },
  {
    title: 'Update portfolio',
    icon: 'Layout',
    color: '#EC4899',
    category: 'networking_career',
    goalType: 'binary',
    target: null,
    unit: null,
    frequency: { type: 'daily', daysOfWeek: [6] },
    defaultReminderTime: '15:00',
  },
  {
    title: 'Connect on LinkedIn',
    icon: 'Link',
    color: '#0A66C2',
    category: 'networking_career',
    goalType: 'count',
    target: 5,
    unit: 'connections',
    frequency: { type: 'daily', daysOfWeek: [1, 2, 3, 4, 5] },
    defaultReminderTime: '09:30',
  },
]

export const habitCategories = [
  { key: 'content_creative' as const, label: 'Content & Creative' },
  { key: 'learning' as const, label: 'Learning' },
  { key: 'health_fitness' as const, label: 'Health & Fitness' },
  { key: 'networking_career' as const, label: 'Networking & Career' },
]

export default habitGallery
